### ISSUE TITLE
Dataset selection 

### ISSUE THREAD

**Issue by mariam50411** [Mohamedema/NGS_Group_project#2]
which dataset is more suitable?
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE138485
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124535

**Comment by Hadeer-Hassan** [comment]
We choose the 1st data set  with SRA: SRP224575
our reasons: 
1- number of samples 64 "32 Normal and 32 Cancerous" 
2- the data are humongous
